name: Kubernetes deployment

on:
  push:
    branches: [ dev, main ]

jobs:
  build:
    name: Building and Pushing Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Frontend to Amazon ECR (dev)
        id: build-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}

        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          app=frontend
          image_tag="$ECR_REGISTRY/$ECR_REPOSITORY:$app-${GITHUB_REF##*/}-$git_hash"
          docker build -t $image_tag --target $app --target frontend --build-arg GRAPHQL_URI=https://graph-test.holaplex.com/v1 .
          echo "Pushing image to ECR..."
          docker push $image_tag
          echo "::set-output name=image::$image_tag"

      - name: Build, tag, and push signer to Amazon ECR (dev)
        id: build-signer-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}

        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          app=signer
          image_tag="$ECR_REGISTRY/$ECR_REPOSITORY:$app-${GITHUB_REF##*/}-$git_hash"
          docker build -t $image_tag --target $app .
          echo "Pushing image to ECR..."
          docker push $image_tag
          echo "::set-output name=image::$image_tag"

      - name: Triggering deployment manifest update in kubes repository
        uses: actions/github-script@v6
        env:
          BRANCH: ${{ github.ref_name }}
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'holaplex',
              repo: 'kubes',
              workflow_id: 'holaplex.yaml',
              ref: process.env.BRANCH
            })
